services:
  - type: web
    name: lucien
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
